language: node_js
node_js:
- '8'
- '9'
- '10'
script:
- yarn add aws-xray-sdk-core@^${XRAY_SDK_VERSION} && yarn test && git checkout -- package.json yarn.lock
after_success: yarn coverage
notifications:
  email:
    on_success: never
    on_failure: always
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
- XRAY_SDK_VERSION=v1.3
- XRAY_SDK_VERSION=v2.0
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  on:
    tags: true
    repo: lifeomic/graphql-resolvers-xray-tracing
    node: '8'
